export const EN_TEXT = {
    LOGO_NAME: "SKINY",
    SIGN_IN: "SIGN IN",
    SIGN_UP: "SIGN UP",
    WELCOME: "Welcome",
    WELCOME_BACK: "Welcome back",
    NAME: "Name",
    USERNAME: "Username",
    PASSWORD: "Password",
    NEXT: "NEXT",
    HI: "Hi",
    LET_US_KNOW: "Let us know",
    SKIN_STATUS: "SKIN STATUS",
    SKIN_ROUTINES: "SKIN ROUTINES",
    SKIN_GOALS: "SKIN GOALS",
    SKIN_IMAGE: "SKIN IMAGE",
    UPLOAD_IMAGE: "Upload your skin images",
    DONE: "DONE",
    NEW_ARRIVALS: "New Arrivals",
    SEE_ALL: "See all",
    FOR_YOU: "FOR YOU",
    SALES: "Sales",
    ADD_TO_CART: "Add to cart",
    PRODUCTS: "PRODUCTS",
    ALL_PRODUCT: "All products",
    TOP_SELLING: "Top selling",
    MASKS: "Masks",
    REVIEW: "Review",
    CART: "CART",
    CHECKOUT: "Checkout",
    DELIVERY_INFORMATION: "Delivery infomation",
    TOTAL: "Total",
    ORDER: "Order",
    ORDER_SUCESSFULLY: "Order sucessfully",
    GOOD_MORNING: "Good morning, ",
    GOOD_AFTERNOON: "Good afternoon, ",
    DIARY: "Diary",
    YOUR_SKIN: "Your skins",
    MESSAGES: "Messages",
    DISCOUNT: "Discounts",
    RATE: "Rate",
    DONE: "DONE",
    DELIVERY: "Delivery",
    BUY_IN_STORE: "Buy in store",
    DELIVERY_FEE: "Delivery fee",
    EMAIL: 'Email',
    DELIVERY_FEE_PRICE: 20000,
    ORDERS: "ORDERS",
    EXPLORE: "EXPLORE",
    WRITE_YOURS: "Write yours"
}